use_frameworks!

platform :ios, '9.0'

target 'ALNTestPodProj_Example' do
  pod 'ALNTestPodProj', :path => '../'

  target 'ALNTestPodProj_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
